// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/62eedc3121a5e28c50473d2e4a9cefbcb9c3957f/angularLocalStorage/angularLocalStorage.d.ts
// Type definitions for AngularLocalStorage 0.1.7
// Project: https://github.com/agrublev/angularLocalStorage
// Definitions by: Horiuchi_H <https://github.com/horiuchi/>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


declare module angular.localStorage {
  interface ILocalStorageService {
    set(key: string, value: any): any;
    get(key: string): any;
    remove(key: string): boolean;
    clearAll(): void;

    bind($scope: ng.IScope, key: string, opts?: {
      defaultValue?: any;
      storeName?: string;
    }): any;
    unbind($scope: ng.IScope, key: string, storeName?: string): void;
  }
}